# Generated by Django 4.1 on 2022-08-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CsvFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("path", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "column_datatype",
                    models.CharField(
                        choices=[
                            ("TEXT", "TEXT"),
                            ("NUMBER", "NUMBER"),
                            ("DATETIME", "DATETIME"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="api.csvfile",
                    ),
                ),
            ],
        ),
    ]
