name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -r requirements-dev.txt
      - run: ./scripts/test.sh